# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/getting-started/

# baseURL = "https://ddd3h.github.io/"
defaultContentLanguage = "ja"

enableRobotsTXT = true
paginate = 20
summaryLength = 30

buildDrafts = false
buildFuture = false

#googleAnalytics = "G-XXXXXXXXX"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 1.0

[outputs]
  home = ["HTML", "RSS", "JSON"]


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true