# -- メインメニュー --
# メインメニューはページトップのヘッダーに表示されます。
# 利用可能なパラメーターは name, pageRef, page, url, title, weight です。
# 
# 最もシンプルなメニュー設定はこちらです:
#   name = このメニューリンクに表示される名前
#   pageRef = ページやセクションのリンクに利用される識別子
#
# デフォルトでは、メニューはアルファベット順に並べられます。
# これは、 weight value で上書き可能です。
# このメニューは weight が低い値から高い値に順に表示されます。

[[main]]
  name = "著者"
  weight = 2

[[main]]
name = "来歴"
parent = "著者"
pageRef = "cv"
weight = 2

[[main]]
name = "研究・開発"
parent = "著者"
pageRef = "res-dev"
weight = 3

[[main]]
name = "講演・口頭発表等"
parent = "著者"
pageRef = "presentation"
weight = 4

[[main]]
name = "受賞"
parent = "著者"
pageRef = "award"
weight = 5


[[main]]
  name = "データ"
  pageRef = "data"
  weight = 100

[[main]]
  name = "投稿"
  pageRef = "posts"
  weight = 30

[[main]]
  name = "カテゴリ"
  pageRef = "categories"
  weight = 40


# -- フッターメニュー --
# このフッターメニューはページ下部のコピーライト表示の前に表示されます。
# 上記のメインメニューと同様に設定できます。

 [[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 10

 [[footer]]
   name = "Categories"
   pageRef = "categories"
   weight = 20
